[build]
builder = "RAILPACK"
buildCommand = "mvn -B -DskipTests clean package"

[deploy]
startCommand = "java -Xms96m -Xmx384m -XX:MaxMetaspaceSize=160m -XX:ReservedCodeCacheSize=64m -XX:MaxDirectMemorySize=64m -jar target/*.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
