CREATE TABLE notification_preferences (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    meal_reminders BOOLEAN NOT NULL DEFAULT TRUE,
    coach_nudges BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE push_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expo_token VARCHAR(255) NOT NULL UNIQUE,
    registration_id VARCHAR(36) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_push_devices_user ON push_devices(user_id, enabled);
CREATE TABLE push_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL REFERENCES notification_events(id) ON DELETE CASCADE,
    device_id BIGINT NOT NULL REFERENCES push_devices(id) ON DELETE CASCADE,
    registration_id VARCHAR(36) NOT NULL,
    kind VARCHAR(16) NOT NULL,
    status VARCHAR(20) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    receipt_id VARCHAR(100),
    last_error VARCHAR(100),
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (notification_id, device_id)
);
CREATE INDEX idx_push_delivery_queue ON push_deliveries(status, next_attempt_at);
