import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useDispatch, useSelector } from 'react-redux';
import Screen from '../../components/common/Screen';
import { toggleTask } from '../../store/slices/planSlice';
import { colors, radius, type } from '../../theme';

export default function DailyPlanScreen() {
  const plan = useSelector((state) => state.plan); const dispatch = useDispatch();
  return <Screen><View style={styles.head}><Text style={styles.kicker}>YOUR PROGRAM</Text><Text style={styles.title}>{plan.title}</Text><Text style={styles.body}>{plan.daysRemaining} days remain in this cycle. Finish at your own pace.</Text></View><View style={styles.progress}><View style={[styles.progressFill, { width: `${(plan.tasks.filter((task) => task.done).length / plan.tasks.length) * 100}%` }]} /></View><Text style={styles.sectionLabel}>TODAY’S RITUALS</Text><View>{plan.tasks.map((task, index) => <Pressable key={task.id} onPress={() => dispatch(toggleTask(task.id))} style={styles.task}><View style={[styles.check, task.done && styles.checkDone]}>{task.done && <Ionicons name="checkmark" size={18} color={colors.white} />}</View><View style={styles.copy}><Text style={[styles.taskTitle, task.done && styles.done]}>{task.title}</Text><Text style={styles.detail}>{task.detail}</Text></View><Text style={styles.number}>0{index + 1}</Text></Pressable>)}</View><View style={styles.quote}><Text style={styles.quoteText}>“Consistency is a direction, not a perfect score.”</Text><Text style={styles.quoteBy}>— COACH MIRA</Text></View></Screen>;
}
const styles = StyleSheet.create({ head: { marginTop: 20, gap: 8 }, kicker: { ...type.label, color: colors.moss }, title: { ...type.display, color: colors.ink }, body: { ...type.body, color: colors.muted, maxWidth: 330 }, progress: { height: 6, borderRadius: 3, backgroundColor: colors.line, marginVertical: 28, overflow: 'hidden' }, progressFill: { height: 6, backgroundColor: colors.accent, borderRadius: 3 }, sectionLabel: { ...type.label, color: colors.muted, marginBottom: 6 }, task: { flexDirection: 'row', alignItems: 'center', paddingVertical: 20, borderBottomColor: colors.line, borderBottomWidth: StyleSheet.hairlineWidth }, check: { width: 28, height: 28, borderRadius: 14, borderWidth: 1.5, borderColor: colors.moss, alignItems: 'center', justifyContent: 'center' }, checkDone: { backgroundColor: colors.moss }, copy: { flex: 1, marginLeft: 14 }, taskTitle: { color: colors.ink, fontSize: 16, fontWeight: '800' }, done: { textDecorationLine: 'line-through', color: colors.muted }, detail: { color: colors.muted, marginTop: 4 }, number: { color: colors.line, fontSize: 18, fontWeight: '800' }, quote: { marginTop: 34, backgroundColor: colors.accentSoft, padding: 25, borderRadius: radius.lg }, quoteText: { color: colors.ink, fontSize: 19, lineHeight: 27, fontWeight: '600' }, quoteBy: { ...type.label, color: colors.moss, marginTop: 15 } });

